getwd()
data <- read.table("test/X_test.txt")
data <- rbind(data,  read.table("train/X_train.txt"))
activity <- read.table("test/y_test.txt")
activity <- rbind(activity, read.table("train/y_train.txt"))
activity$V1 <- as.factor(activity$V1)
subject <-  read.table("test/subject_test.txt")
subject <- rbind(subject, read.table("train/subject_train.txt"))
data <- cbind(data, subject, activity)
data <- data[, c(which(grepl("mean()", read.table("features.txt")$V2, fixed=TRUE)),which(grepl("std()", read.table("features.txt")$V2, fixed=TRUE)), 562, 563)] 
activity <- read.table("activity_labels.txt")
levels(data$V1.2) <- list(WALKING = 1, WALKING_UPSTAIRS = 2, WALKING_DOWNSTAIRS = 3, SITTING = 4, STANDING  = 5, LAYING = 6)
names(data) <- c(as.character(read.table("features.txt")[c(grep("mean()", read.table("features.txt")$V2, fixed=TRUE)),2]), as.character(read.table("features.txt")[c(grep("std()", read.table("features.txt")$V2, fixed=TRUE)),2]), "subject", "activity")
data$subject <- as.factor(data$subject)
# in case the package "reshape2" is not installed, use install.packages(reshape2) 
# to install the package before continuing with the script
library("reshape2")
tidy <- dcast(melt(data, id.vars= c("subject", "activity")), subject + activity ~ variable , fun=mean)
write.table(tidy, file = "tidy_dataset.txt", row.names=FALSE)
